apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-from-github-repo
spec:
  generators:
    - git:
        repoURL: https://github.com/tryrocket-cloud/home-ops.git
        revision: main
        directories:
          - path: k8s/*
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/your-github-org/your-repo.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
