apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx # Selects the pods with this label
  ports:
    - protocol: TCP
      port: 80 # The port that the service will expose
      targetPort: 80 # The port the pod listens to (defined in Deployment)
  type: ClusterIP # This is the default; other options are NodePort or LoadBalancer
